# Generated by Django 4.2 on 2023-05-11 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_endereco_bairro'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='bairro_nac',
            field=models.CharField(default='', max_length=80, verbose_name='Bairro_nac'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endereco',
            name='cidade_nac',
            field=models.CharField(default='', max_length=120, verbose_name='Cidade_nac'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endereco',
            name='estado_nac',
            field=models.CharField(default='', max_length=120, verbose_name='Estado_nac'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endereco',
            name='pais_nac',
            field=models.CharField(default='', max_length=120, verbose_name='Pais_nac'),
            preserve_default=False,
        ),
    ]
