# Generated by Django 4.2 on 2023-07-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_cidade_estado_remove_estado_pais_regiao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.IntegerField(null=True, verbose_name='Telefone'),
        ),
    ]
