# Generated by Django 4.2 on 2023-07-15 02:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_usuario_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anexos',
            name='anexos',
        ),
        migrations.RemoveField(
            model_name='anexos',
            name='cadastro',
        ),
        migrations.RemoveField(
            model_name='anexos',
            name='data_validacao_anexo',
        ),
        migrations.RemoveField(
            model_name='anexos',
            name='editoras',
        ),
        migrations.RemoveField(
            model_name='anexos',
            name='instituicoes',
        ),
        migrations.AddField(
            model_name='anexos',
            name='arquivo_pdf',
            field=models.FileField(default='default.pdf', upload_to='pdfs/'),
        ),
        migrations.AddField(
            model_name='anexos',
            name='data_cadastro',
            field=models.DateField(default=datetime.date.today, verbose_name='Data_Cadastro'),
        ),
        migrations.AddField(
            model_name='anexos',
            name='deferido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artigos_deferidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anexos',
            name='nome_editora',
            field=models.CharField(default='Editora Padrão', max_length=100, verbose_name='Nome da Editora'),
        ),
        migrations.AddField(
            model_name='anexos',
            name='nome_instituicao',
            field=models.CharField(default='Instituição Padrão', max_length=200, verbose_name='Nome da Instituição'),
        ),
        migrations.AddField(
            model_name='anexos',
            name='status',
            field=models.CharField(choices=[('pendente', 'Avaliação Pendente'), ('deferido', 'Deferido'), ('indeferido', 'Indeferido')], default='pendente', max_length=20),
        ),
        migrations.AddField(
            model_name='anexos',
            name='titulo',
            field=models.CharField(default='Título Padrão', max_length=50, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='anexos',
            name='usuario',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='anexos',
            name='descricao',
            field=models.CharField(max_length=350, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='anexos',
            name='nome_periodico',
            field=models.CharField(max_length=50, verbose_name='Nome do Periódico'),
        ),
        migrations.AlterField(
            model_name='anexos',
            name='resumo',
            field=models.CharField(max_length=1500, verbose_name='Resumo'),
        ),
        migrations.DeleteModel(
            name='Editoras',
        ),
        migrations.DeleteModel(
            name='Instituicoes',
        ),
    ]
