# Generated by Django 4.2 on 2023-07-15 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_anexos_anexos_remove_anexos_cadastro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anexos',
            name='resumo',
        ),
    ]
