# Generated by Django 4.2 on 2023-07-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_anexos_resumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexos',
            name='data_deferimento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
